version: "3"

services:
  php:
    image: devilbox/php-fpm-7.4
    container_name: "php-fpm-74"
    environment:
      - PHP_MODULES_ENABLE=ffi
    volumes:
      - "./app:/var/www/default/htdocs"

  app:
    image: app-php74
    build:
      context: ./docker/
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php-fpm-74
    volumes:
      - "./app:/var/www/default/htdocs"
    ports:
      - "80:80"
    depends_on:
      - php
